<?php
echo '<title>' . $name . '</title>' . "\n";
echo '		<style>' . "\n";
echo '		body' . "\n";
echo '		{' . "\n";
echo '			margin: 0px;' . "\n";
echo '			background-color: #0099FF;' . "\n";
echo '		}' . "\n";
echo '		#container' . "\n";
echo '		{' . "\n";
echo '			width: 900px;' . "\n";
echo '			margin: 0px auto;' . "\n";
echo '			background-color: #FFFFFF;' . "\n";
echo '		}' . "\n";
echo '		#navigation' . "\n";
echo '		{' . "\n";

echo '		}' . "\n";
echo '		#left' . "\n";
echo '		{' . "\n";
echo '			float: left;' . "\n";
echo '			width: 435px;' . "\n";
echo '			border: 1px solid #000000;' . "\n";
echo '			margin-top: 10px;' . "\n";
echo '			margin-bottom: 10px;' . "\n";
echo '			margin-right: 5px;' . "\n";
echo '			padding: 5px;' . "\n";
echo '		}' . "\n";
echo '		#right' . "\n";
echo '		{' . "\n";
echo '			float: right;' . "\n";
echo '			width: 435px;' . "\n";
echo '			border: 1px solid #000000;' . "\n";
echo '			margin-top: 10px;' . "\n";
echo '			margin-bottom: 10px;' . "\n";
echo '			padding: 5px;' . "\n";
echo '		}' . "\n";
echo '		#footer' . "\n";
echo '		{' . "\n";
echo '			clear: both;' . "\n";
echo '			width: 888px;' . "\n";
echo '			border: 1px solid #000000;' . "\n";
echo '			padding: 5px;' . "\n";
echo '		}' . "\n";
echo '		.navigation a:link, a:visited' . "\n";
echo '		{' . "\n";
echo '			width: 177px;' . "\n";
echo '			text-decoration: none;' . "\n";
echo '			background-color: #33BBEE;' . "\n";
echo '			color: #000000;' . "\n";
echo '			display: inline-block;' . "\n";
echo '			margin-right: 1px;' . "\n";
echo '			text-align: center;' . "\n";
echo '			border-bottom: 1px solid #3399EE;' . "\n";
echo '			border-top: 1px solid #3399EE;' . "\n";
echo '			border-left: 1px solid #3399EE;' . "\n";
echo '			border-right: 1px solid #3399EE;' . "\n";
echo '		}' . "\n";
echo '		</style>' . "\n";
echo '		<div id="container">' . "\n";
echo '		<h1 align="center">Wumbo Park District</h1>' . "\n";
echo '		<h3 align="center">' . $name . '</h3>' . "\n";
echo '		<hr>' . "\n";

echo '		 <div id="navigation">' . "\n";
echo '			<span class="navigation">' . "\n";
echo '				 <a href="index.php">Home</a><a href="games.php">Games</a><a href="team.php">Teams</a><a href="contact.php">Contact Us</a><a href="login.php">Member Page</a>' . "\n";
echo '			</span>' . "\n";
echo '		</div>' . "\n";
?>
